# Generated by Django 5.1 on 2024-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisterMedico",
            fields=[
                ("id_Medico", models.AutoField(primary_key=True, serialize=False)),
                ("medicoName", models.CharField(max_length=100, verbose_name="Nome")),
                ("medicoDateNasc", models.DateField(verbose_name="Data de Nascimento")),
                ("medicoCPF", models.CharField(max_length=11, verbose_name="CPF")),
                ("medicoCEP", models.CharField(max_length=100, verbose_name="CEP")),
                ("medicoTel", models.CharField(max_length=11, verbose_name="Telefone")),
                (
                    "medicoEmail",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                ("password", models.CharField(max_length=1000)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
