# Generated by Django 5.1 on 2024-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_registermedico_pagmes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterPacientes",
            fields=[
                ("id_Paciente", models.AutoField(primary_key=True, serialize=False)),
                ("pacienteName", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "pacienteDateNasc",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("pacienteCPF", models.CharField(max_length=11, verbose_name="CPF")),
                ("pacienteCEP", models.CharField(max_length=100, verbose_name="CEP")),
                (
                    "pacienteTel",
                    models.CharField(max_length=11, verbose_name="Telefone"),
                ),
                (
                    "pacienteEmail",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                ("password", models.CharField(max_length=1000)),
                ("mensalidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pagMes", models.BooleanField(default=False)),
            ],
        ),
    ]
