# Generated by Django 5.1 on 2024-09-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_registerpacientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerpacientes",
            name="mensalidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Mendalidade"
            ),
        ),
    ]
