# Generated by Django 5.1 on 2024-09-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0007_alter_registeragenda_nome_medico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeragenda",
            name="nome_medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registrations.registermedico",
            ),
        ),
        migrations.AlterField(
            model_name="registeragenda",
            name="nome_paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registrations.registerpacientes",
            ),
        ),
    ]
