# Generated by Django 5.1 on 2024-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0008_alter_registeragenda_nome_medico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeragenda",
            name="cpf_paciente",
            field=models.CharField(max_length=200),
        ),
    ]
