# Generated by Django 5.1 on 2024-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0009_alter_registeragenda_cpf_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterFinanca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receita", models.DecimalField(decimal_places=2, max_digits=10)),
                ("despezas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mesP", models.DateField()),
                ("obs", models.TextField()),
            ],
        ),
    ]
